export const USOS_SIGPAC: Record<string, string> = {
  CF: "Asociación Cítricos-Frutales",
  CS: "Asociación Cítricos-Frutales de Cáscara",
  CV: "Asociación Cítricos-Viñedo",
  FF: "Asociación Frutales-Frutales de Cáscara",
  OC: "Asociación Olivar-Cítricos",
  CI: "Cítricos",
  AG: "Corrientes y Superficies de Agua",
  ED: "Edificaciones",
  EP: "Elementos del Paisaje",
  FO: "Forestal",
  FY: "Frutales",
  FS: "Frutos Secos",
  FL: "Frutos Secos y Olivar",
  FV: "Frutos Secos y Viñedo",
  TH: "Huerta",
  MT: "Matorral",
  IM: "Improductivos",
  IV: "Invernaderos y Cultivos Bajo Plástico",
  OV: "Olivar",
  OF: "Olivar - Frutal",
  OP: "Otros Cultivos Permanentes",
  PS: "Pastizal",
  PR: "Pasto Arbustivo",
  PA: "Pasto con Arbolado",
  TA: "Tierras Arables",
  CA: "Viales",
  VI: "Viñedo",
  VF: "Viñedo - Frutal",
  VO: "Viñedo - Olivar",
  ZV: "Zona Censurada",
  ZC: "Zona Concentrada no incluida en la Ortofoto",
  ZU: "Zona Urbana"
};
